---

- hosts: webserver
  become: yes
  become_user: root
  gather_facts: yes


  tasks:
    - name: Check if Apache is already installed
      shell: dpkg -s apache2 | grep Status
      register: apache2_is_installed
      failed_when: no


    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: apache2_is_installed.rc == 1


    - name: Print result
      debug:
        msg: "{{ apache2_is_installed }}"
